# SPDX-FileCopyrightText: The mpeg-audio-header authors
# SPDX-License-Identifier: CC0-1.0

version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
